apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test
spec:
  ports:
  - port: 80
    name: web
  selector:
  # Change this selector to match your application's labels
    app: nginx
  type: NodePort

