apiVersion: v1
kind: Pod
metadata:
  name: web 
  namespace: test
  labels:
    app: web
spec:
  containers:
    # This is where the application container would go, for example
    # - name: some-name
    # image: some-image
    # This is the ambassador container
    - name: web
      image: yeasy/simple-web

