apiVersion: v1
kind: Pod
metadata:
  name: web-undertest 
  namespace: test
  labels:
    app: experiment 
spec:
  containers:
    # This is where the application container would go, for example
    # - name: some-name
    # image: some-image
    # This is the ambassador container
    - name: exp
      image: yeasy/simple-web

