apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: test
  labels:
    app: web
spec:
  ports:
  - port: 80
    name: web
  selector:
  # Change this selector to match your application's labels
    app: web

