apiVersion: v1
kind: Service
metadata:
  name: experiment
  namespace: test
  labels:
    app: experiment
spec:
  ports:
  - port: 80
    name: web
  selector:
    # Change this selector to match your application's labels
    app: experiment

